
# docker-compose.yml
services:
  database:
    image: postgres:15-alpine
    container_name: participation_tracker_db
    environment:
      POSTGRES_USER: tracker_user
      POSTGRES_PASSWORD: jdETkY08Gw0Y4gTQ
      POSTGRES_DB: participation_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: participation_tracker_redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: participation_tracker_app
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
      # IMPORTANT: set this to the URL you'll actually use in your browser.
      # If you access via server IP, use http://<server-ip>:3010
      NEXTAUTH_URL: "http://localhost:3010"
      NEXTAUTH_SECRET: "replace-with-long-random"
      DATABASE_URL: "postgresql://tracker_user:jdETkY08Gw0Y4gTQ@database:5432/participation_tracker?connect_timeout=15"
    ports:
      - "3010:3000"

volumes:
  postgres_data:
